### PR TITLE
swizzle not found to fire 'page-not-found' event

### PR DESCRIPTION
**Pull request by andrewm4894**
This will fire a "page-not-found" event each time a user hits the not found page in learn. 

Here is an example user i did this with: https://app.posthog.com/person/183d15d0923d8a-09b312e5bdee77-26021f51-15f900-183d15d09248dd#activeTab=events

We will be able to use this to easily get volume based list of 404's users are actually hitting each day/week and clean them up based on traffic. 

image

### CODE REVIEW

**Comment by andrewm4894** [comment]
this is based off this GH discussion: https://github.com/facebook/docusaurus/discussions/6030#discussioncomment-1719187

**Review by DShreve2 — APPROVED** [review]

**Comment by andrewm4894** [comment]
ill test and validate once more when live.

**Comment by andrewm4894** [comment]
yep all working fine:

image

**Comment by tkatsoulas** [comment]
cc @Ancairon 

keep in mind, a new component that needs swizzling (related to docusaurus-upgrade-to-2.1)

**Comment by andrewm4894** [comment]
p.s. someone mentioned we could `wrap` instead and might be a little less code to duplicate. I just ejected in case we ever want to customize that 404 page anyway.

https://github.com/facebook/docusaurus/discussions/6030#discussioncomment-3870472

**Pull request merged**
