### PR TITLE
Reuse component for Collector documentation

### PR DESCRIPTION
**Pull request by kickoke**
The file `_config.mdx` is a component for the ["Configuration" section](https://netdata.atlassian.net/wiki/spaces/DT/pages/1397161985/Topic+types+and+templates#Collector-reference-template) in the collectors documentation.  

The goal is to pass the file name of the configuration file into a variable, so the component can render the same information but with a changing filename. 

Currently, the reuse doesn't work because of the following error in `_config.mdx`.

> Module parse failed: Unexpected token (3:3)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | export const pluginFile = "Default Value";
> | 
> > To edit the <>{props.pluginFile}</> configuration file:
> | 
> | 1. Navigate to the [Netdata config directory](/docs/configure/nodes#the-netdata-config-directory).

### CODE REVIEW

**Comment by tkatsoulas** [comment]
Hi there, I look into this over the weekend.

In the latest commit you can see how this method could work (don't pay attention on the paths, just the implementation), unfortunately this functionality included in 
docusaurus v2.0.0-beta.3 but also in this version (and the later on) there is this issue that we must examine

https://github.com/facebook/docusaurus/issues/6072

So we pause this effort for now. 

Next steps:
- update docusaurus in a newer version (we need this for other reasons also)
- check if this implementation works

l

**Comment by kickoke** [comment]
@tkatsoulas  Just to document the current state: 

You've tested this file on 2.0.0beta15 and the reuse in the code block and the list item didn't work, right? 
Do you think it could work if we put an HTML inline tag around this, which is invisible? 
Something like <a> without a link maybe?

**Comment by tkatsoulas** [comment]
> You've tested the _collector_config.mdx file on 2.0.0beta15, right?
yes
> Let's test the _config.mdx file because this has the component markup (<>{props.pluginFile}</>) in all instances and maybe it works then.

You can check the `check_reuse_mdx_in_beta_15` branch, still the issue remains

**Comment by kickoke** [comment]
Handled by #930

**Pull request closed without merging**
