### PR TITLE
Remove old Learn and old ingested files from root directory

### PR DESCRIPTION
**Pull request by Ancairon**
Closes https://github.com/netdata/learn/issues/1352

@cakrit I read all the files, anything that has a `custom_edit_url` that leads outside of Learn was at some time ingested here, so those are already existing somewhere else, edited or deleted.

The only two that seem to be Learn files are these, check if they have any valuable info, and if they do I'll add them to netdata/netdata somewhere.

[contribute/support.md](https://github.com/netdata/learn/tree/master/contribute/support.md)
[contribute/license.md](https://github.com/netdata/learn/tree/master/contribute/license.md)

I am already deleting them in this PR, so if you agree that we don't need them, just approve, otherwise, let me know what should be moved to netdata/netdata.

### CODE REVIEW

**Comment by Ancairon** [comment]
The preview is expected to fail, a commit that removes the links to these orphan pages from version 1.37.x is following

**Comment by Ancairon** [comment]
@cakrit @tkatsoulas Removing guides means that we need to remove them from the docusaurus.config.js, but also means that https://learn.netdata.cloud/guides needs to go, because:
- It will lead to 404s
- It is manually generated

**Comment by cakrit** [comment]
These two exist already elsewhere:

[contribute/support.md](https://github.com/netdata/learn/tree/master/contribute/support.md)
[contribute/license.md](https://github.com/netdata/learn/tree/master/contribute/license.md)


The guides are already being brought in to the new version of learn from netdata/netdata. But I don't want new 404s right now,
so we'll remove the /guides URL only after we get rid of the legacy stuff and have the 404 redirects to search in plac.e

**Comment by cakrit** [comment]
in short, either remove the guides deletion from this PR, or we'll merge it much later.

**Comment by Ancairon** [comment]
Reverted the guides, will re-request review once the deploy preview is done

**Pull request merged**
