### PR TITLE
Implement addition of our API inside Learn

### PR DESCRIPTION
**Pull request by Ancairon**
Closes https://github.com/netdata/learn/issues/1209

This PR adds our API to `/api`, and an entry in the top navbar to lead to that.

To achieve this, we have to ingest the .json file and send it to `/api.json`
then some additional changes inside `docusaurus.config.js` and it all functions pretty nicely.

Afterwards it is just up to editing the .json file so we present the sections as we like.

### CODE REVIEW

**Comment by andrewm4894** [comment]
looks good to me - will wait until ready for review to look more deeper but seems pretty nice.

**Comment by Ancairon** [comment]
@andrewm4894 I changed it to take the .json file from `netdata/netdata`, this :point_right: [`/web/api/netdata-swagger.json`](https://github.com/netdata/netdata/blob/master/web/api/netdata-swagger.json) and I think it is ready for review.

**Comment by andrewm4894** [comment]
@Ancairon might need to update from master since that other PR touched the yarn lock

**Comment by Ancairon** [comment]
will rebase, yup :+1:

**Comment by Ancairon** [comment]
well, that didn't fix it, I'll try to rebase, because this is an automated file it is a bit hectic to fix conflicts

**Comment by Ancairon** [comment]
@andrewm4894 it should now be fixed I think, no merge conflicts.

**Review by cakrit — CHANGES_REQUESTED** [review]
- Needs css changes, especially on the right side with the parameters and calls, plus the newline on the response status codes. Get help from @christophidesp 
- api/analyze-all-the-metrics-to-find-their-correlations should be removed from swagger completely
- I'd like the actual endpoint shown a bit more prominently somehow. I can only see /api/v1/data on the right side now.
- The intro page needs some love.

**Comment by Ancairon** [comment]
> api/analyze-all-the-metrics-to-find-their-correlations should be removed from swagger completely
> 
> The intro page needs some love.

There is work currently being done in those files for the api/v2, should we decide who will do the change and when so we don't step into each other's toes? This is not a functional change in the mechanism proposed in this PR, it is a change needed in the source file.

> I'd like the actual endpoint shown a bit more prominently somehow. I can only see /api/v1/data on the right side now.

This might be fixable by "swizzling" the component, with some sort of word-wrap in the box. Albeit, the endpoint is also presented at the top, along with the request type.

**Comment by andrewm4894** [comment]
asked about how the upstream docs maintained here: https://netdata-cloud.slack.com/archives/CSD2D3NTG/p1678889683229689

so i guess would need PR in netdata/netdata if wanted to remove docs for `/api/v1/metric_correlations` for example

**Comment by andrewm4894** [comment]
ps another option is this too in case we think is nice or something https://github.com/rohit-gohri/redocusaurus/

https://redocusaurus.vercel.app/docs/nested/nested-1

in case gives some more flexibility potentially, not sure but just wanted to mention.

**Comment by Ancairon** [comment]
@andrewm4894 

1. Got it, but we should see if the guys have more changes to do, as it might be irritating making merge conflicts for them
2. I like the second one

**Comment by Ancairon** [comment]
We changed the way we are going to implement this feature, more info in the related issue.

**Pull request closed without merging**
