### PR TITLE
Update navigation, remove guides and contribute sections, update the favicon and the main logo

### PR DESCRIPTION
**Pull request by Ancairon**
After some discussion we decided that the navigation in Learn should be:

NETDATA logo -> link to main site
Blog -> home page of the blog
Use cases -> blogposts that have the 'how-to' tag
Community -> link to community
App -> link to the app

So the "Learn" text was removed from the logo, and the sections regarding guides and contribution were removed too.
Note that if we plan to use versioning, this should be merged after we archive the current version.

### CODE REVIEW

**Review by DShreve2 — APPROVED** [review]

**Comment by tkatsoulas** [comment]
@Ancairon before merge:

why you delete all the 
`/contribute/*`

What's the plan for the current `guides`?

**Comment by Ancairon** [comment]
> why you delete all the /contribute/* files?

We discussed with @DShreve2 and @andrewm4894 and resulted that we don't want the contribute link in the next iteration at the navbar, and because they would be hidden I removed them, as it seems we got some contributing info under /docs/contribute in our main github. The question remains what we will do with them, the info inside lies also a bit towards our developers guidelines, and the rest is a bit outdated, so in the near future we could spin another version of this, but tidied up, not half in netdata/learn and half ingested from netdata/netdata. What are your thoughts guys?

> What's the plan for the current guides?

I think David was clear about this, we don't want them in the next iteration, Use Cases will replace them.

**Comment by DShreve2** [comment]
> > why you delete all the /contribute/* files?
> 
> We discussed with @DShreve2 and @andrewm4894 and resulted that we don't want the contribute link in the next iteration at the navbar, and because they would be hidden I removed them, as it seems we got some contributing info under /docs/contribute in our main github. The question remains what we will do with them, the info inside lies also a bit towards our developers guidelines, and the rest is a bit outdated, so in the near future we could spin another version of this, but tidied up, not half in netdata/learn and half ingested from netdata/netdata. What are your thoughts guys?
> 
> > What's the plan for the current guides?
> 
> I think David was clear about this, we don't want them in the next iteration, Use Cases will replace them.

Yeah, essentially this. We'll repurpose the files into a new place, but the Guides are really kind of dead in terms of traffic. We can even leave them up, maybe, so backlinks don't die for now, until we repurpose all the good ones, but I'm looking to remove that part of the menu so we don't drive people to them, and replace it with the "how to" sections the PMs are working on.

**Comment by Ancairon** [comment]
Cool, so @DShreve2 do you want me to put them back in, along with the contribute ones? And just remove the links as a change?

**Comment by DShreve2** [comment]
> Cool, so @DShreve2 do you want me to put them back in, along with the contribute ones? And just remove the links as a change?

Yeah, let's do that for now and rediscuss Monday morning, @Ancairon

**Comment by Ancairon** [comment]
@DShreve2 I did the changes, lets check the preview once it is done, guides and contribute now should be accessible.

**Review by tkatsoulas — APPROVED** [review]

**Pull request merged**
