### PR TITLE
add `data-track` attributes to thumbs up/down

### PR DESCRIPTION
**Pull request by andrewm4894**

### CODE REVIEW

**Comment by kickoke** [comment]
@andrewm4894 I think you mentioned that you've set up something in posthog to track these. Do we still need to merge this PR then?

**Comment by andrewm4894** [comment]
It would be better to add this attribute as the work around I have done is very fragile.

**Comment by kickoke** [comment]
@andrewm4894 You got it. 
Any next steps we need to take?

**Comment by andrewm4894** [comment]
Nope, I can test it on the learn site in next couple of days.

**Comment by andrewm4894** [comment]
Yep all good I see the property now in my most recent thump event in PostHog. 

Screenshot_20220326-104738

**Pull request merged**
