### PR TITLE
Upgrade docusaurus to version 2.0.1, along with all the necessary upgrades needed, and add a plugin for future use

### PR DESCRIPTION
**Pull request by Ancairon**
This PR covers the changes on the files listed below:

### `docusaurus.config.js`
- Add the `docusaurus-theme-openapi-docs` theme for future use with the `docusaurus-plugin-openapi-docs`. This will allow proper rendering of future API docs generated form `.yaml` files.  (lines 13-14)
- The old custom search component wasn't working with the new update and there was little to no documentation on its structure, so I added `@easyops-cn/docusaurus-search-local` as an alternative, from my testing the results at the moment are similar with our old search, not bad, but not perfect due to our duplicate pages, albeit with a better UI than before. (lines 16-26)
- With the new Docusaurus update, the hidable sidebar is configured in another way, added it. (lines 32-36)
- With the update of the `posthog-docusaurus` plugin to version 2.0.0, a new configuration structure was needed. (lines 154-161)
- Add the theme configuration for the `docusaurus-plugin-openapi-docs` plugin, we now use `docusaurus-theme-openapi-docs` as our theme (in the future there will be generated API docs that will leverage the customizations of this theme) it is an extended version of the classic theme.

### `netlify.toml`
- Upgrade `node` version to `16.14.2`

### `package.json`

- Upgrade Docusaurus to `v2.0.1`
- Upgrade `posthog-docusaurus` to version `v2.0.0`

### `custom.css`

- Override the `.markdown ol > li::before` element to properly display numbered lists.
- Override the `markdown pre` element with some visual additions (aids in the future rendering of API docs)
- With the new Docusaurus update the bredcrumbs home icon is misaligned in our configuration, so I overrode the `breadcrumbs_link` element to align everything in the breadcrumbs properly.

### `src/theme/ApiItem/index.js`

- Migrated the `DocItem` swizzle code to the `ApiItem` swizzle, and reformat the file.

### `src/theme/ApiItem/custom.module.css`

- Use the respective file from the `DocItem` swizzle.

---

Removed the DocItem swizzle (not needed)
Removed the SearchBar and the Seo swizzles as they were causing problems with the new update.

### CODE REVIEW

**Comment by Ancairon** [comment]
This also closes #1209

**Comment by tkatsoulas** [comment]
Started the review, my first notes/thoughts: 

1. We need to take a conscious decision on what we lose/gain (config options, limitation on upgrading etc etc) from changing the theme (current: theme-classic -> openapi-docs ) in our docusaurus deployment. Note here: there is a workaround to support multiple themes per doc page: https://stackoverflow.com/questions/64277292/custom-theme-per-doc-page-with-docusaurus-2)

2. The font size is different from the current deployment (slightly larger)

**Comment by andrewm4894** [comment]
i could not install this https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects

```
PS C:\Users\andre\Documents\repos\learn> npm install --save @docusaurus/plugin-client-redirects
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @elastic/react-search-ui@1.5.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@">=0.14.9" from downshift@3.4.8
npm ERR!   node_modules/downshift
npm ERR!     downshift@"^3.2.10" from @elastic/react-search-ui-views@1.5.1
npm ERR!     node_modules/@elastic/react-search-ui-views
npm ERR!       @elastic/react-search-ui-views@"1.5.1" from @elastic/react-search-ui@1.5.1
npm ERR!       node_modules/@elastic/react-search-ui
npm ERR!         @elastic/react-search-ui@"^1.3.3" from the root project
npm ERR!       1 more (the root project)
npm ERR!   peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.1
npm ERR!   node_modules/flux
npm ERR!     flux@"^4.0.1" from react-json-view@1.21.3
npm ERR!     node_modules/react-json-view
npm ERR!       react-json-view@"^1.21.3" from @docusaurus/plugin-debug@2.0.0-beta.18
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @elastic/react-search-ui@1.5.1
npm ERR! node_modules/@elastic/react-search-ui
npm ERR!   @elastic/react-search-ui@"^1.3.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.0" from @elastic/react-search-ui@1.5.1
npm ERR!   node_modules/@elastic/react-search-ui
npm ERR!     @elastic/react-search-ui@"^1.3.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\andre\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andre\AppData\Local\npm-cache\_logs\2022-11-11T13_56_21_165Z-debug-0.log
```

Does this mean we cant support rediectrs until we fix all this?

**Review by tkatsoulas — APPROVED** [review]

**Comment by tkatsoulas** [comment]
Wrap up for merging: 

1. Upgraded docusaurus to 2.1.0
2. Due to incompatibility of the old search bar we added the search  bar plugin for `@easyops-cn/docusaurus-search-local`, which automatically index all the  current document not only  based on the previous custom metadata 
3. Follow up on the two (above. Remove the work of the swizzled components (`src/theme/SearchBar.js`, `src/theme/Seo/index.js`)
4. We have a feedback form for each doc, to make it work in the past we used to swizzle the whole DocItem structure, add by applying our changes and rebuild it again (note: the whole thing mdx content, sidebars, breadcrumps etc etc) . To the best of my knowledge, this introduced much friction in the actual upgrade (including the one from beta.0 to beta.18). With this in mind, we decided to swizzle the MDXcontent instead (since the feedback form must be available in all MDX content) and add the feedback form there.

**Pull request merged**
