### PR TITLE
Adding video to anomaly advisor learn page

### PR DESCRIPTION
**Pull request by shyamvalsan**
Adding a video, and relocating the Note section to the end of the page.

### CODE REVIEW

**Review by andrewm4894 — COMMENTED** [review]
Hmm unsure if learn will just render the video. Thoughts @DShreve2 ?

**Comment by tkatsoulas** [comment]
I need to:

1. Verify that the packages (react player and it's dependencies are stable to use
2. Make it responsive to mobile views

**Comment by DShreve2** [comment]
> Hmm unsure if learn will just render the video. Thoughts @DShreve2 ?

@tkatsoulas is looking into this. Will report back.

**Comment by shyamvalsan** [comment]
Regarding the video - I initially thought of uploading it as a gif, but guithub and it's 10MB limit put me off (we could still upload the gif and link to it of course)

**Comment by shyamvalsan** [comment]
@DShreve2 @tkatsoulas are we good to merge this PR?

**Comment by andrewm4894** [comment]
This looks good to me. @shyamvalsan you can see it at the preview link from the netlifly boy. I had a look and all looks good to me. 

Thanks @tkatsoulas !

**Comment by andrewm4894** [comment]
So i think we just need @DShreve2 to merge (not sure who else can).

**Comment by tkatsoulas** [comment]
Haven't check the responsiveness, give me on sec

**Comment by tkatsoulas** [comment]
> Regarding the video - I initially thought of uploading it as a gif, but guithub and it's 10MB limit put me off (we could still upload the gif and link to it of course) @DShreve2 @tkatsoulas

In these situations we upload the gif somewhere else (G drive, amazon etc) and add it in learn as an external resource. It's good though to have videos in learn so let's use the current video for this effort.

**Pull request merged**
