### PR TITLE
Feature-ingest multiple branches

### PR DESCRIPTION
**Pull request by tkatsoulas**
Hello everyone,

This PR updates the ingest script and adds the support to specify the user(forked) and branch for every repository it ingests docs from. This will help us when we are building the docs locally.

Before merging it, we must make sure that this change does not interact with any other build workflow.

### CODE REVIEW

**Comment by kickoke** [comment]
@tkatsoulas do you mean we can ingest forks from: kickoke/netdata? 

Another thing that I discovered: 
If we trigger the ingest script manually, we can specify a branch. I think this lets us specify a branch on the learn repo, though so it might not be useful in our case.

image

**Comment by tkatsoulas** [comment]
> @tkatsoulas do you mean we can ingest forks from: kickoke/netdata?
Yes! make sure you rebase your fork regularly from the upstream branch
> Another thing that I discovered: If we trigger the ingest script manually, we can specify a branch. I think this lets us specify a branch on the learn repo, though so it might not be useful in our case.
>
> image

This is an option to run the workflow from a specific branch IN this repo, not to ingest from different branches. 
For example: If I wanted to test the workflow for the current PR (the new ingest script), I would change that option to `feature-ingest-multiple-branches`

**Comment by tkatsoulas** [comment]
> I was looking at the changes again and I am wondering if we need to make changes to the Github action

From what I see, there is no need. The reason why is: The ingest script is called with no arguments in the GHA https://github.com/netdata/learn/blob/master/.github/workflows/ingest.yml#L24. I don't change the defaults in this PR, we just made them variables https://github.com/netdata/learn/blob/master/.github/workflows/ingest.yml#L24 && https://github.com/netdata/learn/pull/891/files#diff-5196acd03ccd184706575590b70862de825e6d0b7a30eab416bdd38f094c0f84R395-R414

But, I need to verify that in the actual deployment we don't somehow call the ingest script with the previous method https://github.com/netdata/learn/pull/891/files#diff-5196acd03ccd184706575590b70862de825e6d0b7a30eab416bdd38f094c0f84L11-L18

> Two things:
>
> We probably need to rebase staging to avoid that it's getting stale.
> @Ancairon is working on staging for the cheat sheet.

I will sync with @Ancairon to test this in staging.

**Comment by kickoke** [comment]
@tkatsoulas Hey Taso, just checking in about this. Were you able to test the updated ingest script so far? :)

**Comment by kickoke** [comment]
@tkatsoulas 
Just an FYI: I left a comment for the readme but other than that, I can't verify if the code works or not.

**Comment by tkatsoulas** [comment]
Thanks for the heads up.

**Pull request closed without merging**
